export type ProjectVisualSpec =
  | { type: "image"; src: string }
  | { type: "terminal" }
  | { type: "workflow" }
  | { type: "code" }
  | { type: "chat" }
  | { type: "chart" };

export type Project = {
  slug?: string;
  title: string;
  category: string;
  year: string;
  status: string;
  onHomepage: boolean;
  featured: boolean;
  accent: "cyan" | "purple" | "pink";
  description: string;
  stack: string[];
  links: { github?: string; live?: string };
  visual: ProjectVisualSpec;
  overview?: string;
  architecture?: string[];
  keyDecisions?: string[];
  challenges?: string[];
};

export const PROJECTS: Project[] = [
  {
    slug: "job-hunter-bot",
    title: "Job Hunter Bot",
    category: "AI & Automation",
    year: "2026",
    status: "Live",
    onHomepage: true,
    featured: true,
    accent: "cyan",
    description:
      "Daily AI job scraper that scores postings against my candidate profile using Claude, logs only 80+ score matches, auto-generates tailored cover letters, and sends an HTML email digest every morning.",
    stack: ["Python", "Claude API", "Modal", "httpx", "BeautifulSoup", "feedparser", "Google Sheets API", "Gmail SMTP"],
    links: { github: "https://github.com/sazanyogi" },
    visual: { type: "terminal" },
    overview:
      "I was job hunting while working full time, and manually checking job boards every day wasn't sustainable. Job Hunter Bot runs on a schedule, scrapes multiple job boards, scores every posting against my actual candidate profile using Claude, and only surfaces the ones worth my time — complete with a drafted cover letter.",
    architecture: [
      "A Modal scheduled function (modal.Cron) fires once a day at 5am EST — no external cron service or always-on server needed.",
      "Four sources are scraped in one run: LinkedIn and Indeed's public Canada search pages (via httpx + BeautifulSoup, with a spoofed browser User-Agent), Remotive's public JSON API, and We Work Remotely's RSS feeds (via feedparser).",
      "Every posting is normalized into one shared schema, then deduplicated by URL and cheaply pre-filtered by job title keywords and location eligibility — before any LLM call, to keep API cost down.",
      "Surviving postings go to Claude Haiku with a rubric-based scoring prompt (skill match 40 / salary fit 25 / legitimacy 20 / career fit 15 = 100), plus a static candidate-profile string injected into every call.",
      "Only postings scoring 80+ and marked legitimate get written to a Google Sheet — which doubles as a lightweight ATS, with conditional-formatting score gradients, a status dropdown (To Apply/Applied/Interview/Offer/Rejected), and schema-migration logic so the sheet's columns can evolve without losing historical data.",
      "The same top matches get a tailored cover letter generated by Claude, and everything gets bundled into an HTML digest sent over Gmail SMTP.",
    ],
    keyDecisions: [
      "Rubric-weighted prompting instead of a free-form \"rate this job 1-10\" — an explicit point breakdown makes Claude's scoring far more consistent run to run.",
      "Defensive JSON parsing: the prompt asks for JSON only, but the code still strips ```json fences and regex-extracts the object before parsing, since LLMs don't always follow formatting instructions perfectly.",
      "Every scrape source and every Claude call is wrapped independently in try/except — one broken source (a changed HTML structure, a timeout) never kills the rest of the run.",
      "Cheap keyword/location filtering happens before the LLM call, not after — the expensive step only ever runs on postings worth scoring.",
    ],
    challenges: [
      "LinkedIn/Indeed don't offer a scraping-friendly API for guest searches, so their public search HTML is scraped directly with UA spoofing rather than paying for a commercial scraping API.",
      "Google Sheets schema evolution: as I added the Status column later, a migration helper detects the old header layout and upgrades it in place instead of wiping historical applications.",
      "Known limitation: dedup only works within a single run (in-memory), so a job still listed days later can theoretically get re-logged — a good next improvement would be checking against previously logged URLs in the sheet itself.",
    ],
  },
  {
    slug: "ga4-dashboard",
    title: "Click & Cast GA4 Dashboard",
    category: "Data Analytics",
    year: "2026",
    status: "Live",
    onHomepage: false,
    featured: false,
    accent: "purple",
    description:
      "Live marketing analytics dashboard for a real media company. Deployed GA4 tracking on a Next.js production site, then built a Looker Studio dashboard tracking sessions, users, traffic sources, top pages, and time-series trends.",
    stack: ["Next.js", "Google Analytics GA4", "gtag.js", "Looker Studio"],
    links: { live: "https://clickandcast.com" },
    visual: { type: "chart" },
    overview:
      "Click & Cast Inc is a media and content production agency I handle technical operations for. They needed to actually see how their marketing site was performing — sessions, traffic sources, which pages converted — without building a custom analytics backend.",
    architecture: [
      "Google Analytics 4's global site tag (gtag.js) is loaded via Next.js's next/script component with strategy=\"afterInteractive\", placed once in the root layout so every route gets tracked automatically.",
      "The GA4 measurement ID is wired directly into the App Router's shared layout — no per-page tracking code needed, and it's disclosed in the site's privacy policy.",
      "On the reporting side, Looker Studio connects natively to the GA4 property and pulls sessions, users, traffic sources, top pages, and time-series trends — configured entirely in Looker's UI, not in application code.",
    ],
    keyDecisions: [
      "afterInteractive loading strategy specifically — analytics scripts shouldn't block hydration or delay interactivity on a marketing site where load speed matters for conversions.",
      "No custom analytics backend or BigQuery export — for a small agency's marketing site, GA4 + Looker Studio's native connector is the pragmatic choice over building bespoke reporting infrastructure.",
    ],
    challenges: [
      "Being honest about scope here: there's no dashboard application code in this project. The engineering work is the GA4 instrumentation itself; the dashboard is a no-code reporting layer on top. Not every \"dashboard\" needs custom code — knowing when not to over-engineer is part of the job.",
    ],
  },
  {
    slug: "sql-portfolio",
    title: "SQL Interview Portfolio",
    category: "Data Engineering",
    year: "2026",
    status: "Live",
    onHomepage: false,
    featured: false,
    accent: "pink",
    description:
      "10 annotated real-world SQL problems covering window functions (DENSE_RANK, LAG, rolling AVG), CTEs, anti-joins, self joins, and retention rate calculations — all with explanations of the why behind each approach.",
    stack: ["PostgreSQL", "Window Functions", "CTEs", "Aggregations", "Anti-joins"],
    links: { github: "https://github.com/sazanyogi/sql-portfolio" },
    visual: { type: "code" },
    overview:
      "I built this to sharpen my SQL for interviews, and to have something concrete to show rather than just claiming \"I know SQL.\" It's 10 self-contained problems covering the patterns that come up constantly in data interviews — window functions, CTEs, anti-joins — each one written to explain the reasoning, not just the answer.",
    architecture: [
      "Flat structure: a problems/ folder with 10 numbered .sql files (01_top_n_salaries.sql through 10_products_never_sold.sql), each fully self-contained — no shared schema files or test runner needed.",
      "Every file follows the same format: a plain-English problem statement (including edge cases), an ASCII-art sample table showing the schema, a clean solution query (often a CTE), and a closing comment explaining why that approach was chosen over an obvious alternative.",
      "Topics covered: DENSE_RANK for tied rankings, running totals and rolling averages via window functions, month-over-month growth with LAG, anti-joins for \"customers who never ordered,\" self-joins for manager chains, and month-cohort retention-rate calculations.",
    ],
    keyDecisions: [
      "\"Why not the alternative\" framing throughout — e.g. explicitly explaining why DENSE_RANK was chosen over ROW_NUMBER for tied salaries, rather than just presenting a correct query. That's the actual interview skill: justifying a choice, not just producing output.",
      "Deliberately shallow-but-precise: no seed scripts, no expected-output assertions, no test framework — these are meant to be read in a few minutes each, not executed as a suite.",
    ],
    challenges: [
      "Keeping every problem genuinely self-contained (schema + data + solution in one file) so each one can be read in isolation, without needing to jump between files for context.",
    ],
  },
  {
    title: "AI Workflow Automations",
    category: "AI & Automation",
    year: "2025",
    status: "Live",
    onHomepage: true,
    featured: false,
    accent: "cyan",
    description:
      "Serverless API endpoints for n8n automation workflows — email reply generation, data pipeline processing, and AI-assisted decision making. Deployed on Modal with Bearer token auth.",
    stack: ["Python", "FastAPI", "Modal", "n8n", "Anthropic API", "OpenAI API"],
    links: { github: "https://github.com/sazanyogi" },
    visual: { type: "workflow" },
  },
  {
    slug: "scorecast",
    title: "Scorecast",
    category: "Web App",
    year: "2024",
    status: "Live",
    onHomepage: true,
    featured: false,
    accent: "purple",
    description:
      "Real-time sports scoreboard platform for local leagues — live scores, standings, fixtures, and news. An admin dashboard drives live match scoring; every viewer sees updates instantly via Firestore real-time sync.",
    stack: ["Next.js", "TypeScript", "Firebase", "Firestore", "Firebase Auth", "Resend", "Tailwind CSS"],
    links: { live: "https://scorecast.clickandcast.com", github: "https://github.com/sazanyogi/goalnepal" },
    visual: { type: "image", src: "/projects/scorecast.png" },
    overview:
      "Click & Cast covers live sports events, and needed a way to broadcast scores in real time rather than manually updating a static page during a match. Scorecast is a full platform: a public site for scores, standings, and news, and an admin dashboard where a match updater scores a game live and every connected viewer sees it update instantly.",
    architecture: [
      "Next.js App Router with two route groups: (public) for the live site — tournaments, fixtures, standings, clubs, matches, articles, plus auth and club/player registration — and (admin) for the operational dashboard — tournament/club/user management and a live match-scoring console.",
      "Firebase is the entire backend: Firestore for data, Firebase Auth (email/password + Google) for sign-in, and firebase-admin (server-only, inside API routes) for privileged operations — the service account key never reaches the client bundle.",
      "Live score updates use Firestore onSnapshot listeners — the admin's match-control panel applies an optimistic local update on a goal/card tap, then reconciles once Firestore confirms the committed write, reverting cleanly on failure.",
      "A three-tier role model (global role, tournament-scoped roles, club-scoped member roles) gates every write, enforced in both a client-side permissions helper (for UX) and independently in Firestore security rules (for real security) — including a field-level allow-list so a live-scoring session can only touch score fields, nothing else.",
      "Five serverless API routes wrap Resend for transactional email (join-request notifications, match-live alerts, password reset, email verification) with custom branded templates instead of Firebase's default auth emails.",
      "Per-page Open Graph images are generated on the fly by an edge route using next/og, so tournament/match/article links look right when shared on social media.",
    ],
    keyDecisions: [
      "Defense in depth: every write is checked twice — once client-side for UX, once in Firestore rules as the actual security boundary — so a compromised or buggy client can't bypass permissions.",
      "A match's lifecycle (draft → live → completed → locked) is an explicit state machine enforced on both client and server, so a match can't be edited after it's locked and scoring only ever touches the fields it's allowed to.",
      "Privileged Firebase Admin SDK calls are confined strictly to API routes — never imported into anything that ships to the browser.",
      "One read-layer barrel file re-exports all Firestore queries, giving every component a single, SDK-hiding import surface instead of scattering firebase/firestore calls throughout the codebase.",
    ],
    challenges: [
      "Reconciling optimistic UI updates during live scoring against the real-time onSnapshot state without visible flicker or the score briefly reverting.",
      "Push notifications for live match events required a PWA layer (manifest, service worker registration, Firebase Cloud Messaging) wired specifically to the match-live email/notification API route.",
      "Honest lesson: the project still carries unused @supabase/* dependencies and an installed-but-never-imported Tiptap rich text editor — both leftover from earlier direction changes (the News/Articles editor ended up as a simpler plain-textarea CMS instead). A good reminder to prune dependencies once a direction is abandoned, not just stop using them.",
    ],
  },
  {
    slug: "crs-calculator",
    title: "CRS Score Calculator",
    category: "Web App",
    year: "2026",
    status: "Live",
    onHomepage: true,
    featured: true,
    accent: "cyan",
    description:
      "Accurate, mobile-first CRS calculator for Canadian Express Entry — better UX than the official IRCC tool. Supports IELTS, CELPIP, TEF, and TCF with real-time scoring, animated score ring, and full IRCC breakdown.",
    stack: ["Next.js", "TypeScript", "Vercel"],
    links: { github: "https://github.com/sazanyogi/crs-calculator", live: "https://crs.sazan.com.np" },
    visual: { type: "image", src: "/projects/crs-calculator.png" },
    overview:
      "Canada's Express Entry CRS score is notoriously complex — dozens of interacting point tables across age, education, language, and work experience, with different rules depending on marital status. The official IRCC tool works, but its UX is rough. I built a calculator that scores identically to the official grid but is actually pleasant to use, with instant feedback as you fill out the form.",
    architecture: [
      "The scoring logic lives in one pure function, calculateCRS(), with zero React or UI coupling — it takes a plain input object and returns a full breakdown, so it's independently testable and reusable.",
      "All of IRCC's official point tables (age, education, language, work experience, skill transferability, spouse factors) are transcribed as plain constant lookup tables, named after IRCC's own grid sections — including a comment noting that IRCC removed job-offer bonus points in 2024, with that value hardcoded to zero to track the real policy change.",
      "Language test scores (IELTS/CELPIP/TEF/TCF) are normalized to the CLB (Canadian Language Benchmark) scale first, in a separate module — so the core scoring engine only ever deals with CLB 0-10 and has no knowledge of which test was taken.",
      "Every form input change recomputes the score synchronously — the whole calculation is cheap arithmetic over lookup tables, so no debouncing or memoization is needed.",
      "The animated score ring is a plain inline SVG: two overlapping circles, with the foreground stroke's dash-offset driven by score/1200 and animated with a CSS transition — no animation library.",
    ],
    keyDecisions: [
      "Official-grid fidelity as the top priority: constants are named and structured to mirror IRCC's own worksheet, so the code can be audited line-by-line against the real scoring grid rather than trusting one opaque formula.",
      "CLB-as-lingua-franca: rather than writing four parallel scoring paths for each language test, everything funnels through one normalized scale, keeping the core engine small and test-agnostic.",
      "Derived state over stored state: rather than asking \"does your spouse count for points?\" as a raw checkbox, the app computes it live from marital status + spouse's citizenship/PR status + whether they're accompanying — modeling IRCC's actual rule instead of trusting the user to know it.",
    ],
    challenges: [
      "Skill Transferability is the single trickiest part of the CRS grid — it combines education, language, and work experience into capped sub-factors. It's isolated into its own function with named intermediate variables mirroring IRCC's worksheet structure, rather than one dense formula.",
      "Honest lesson learned: the language-to-CLB conversion tables currently exist in two places (the shared conversions module and a duplicate set of dropdown options in the page component) — a real duplication risk if IRCC updates thresholds again, and something worth consolidating to one source next.",
    ],
  },
  {
    slug: "yogi-finance",
    title: "Yogi Finance",
    category: "Web App",
    year: "2024",
    status: "Live",
    onHomepage: true,
    featured: true,
    accent: "cyan",
    description:
      "AI-powered personal finance tracker for individuals and couples. Upload any bank statement — Gemini extracts and categorizes every transaction automatically, with Claude powering automatic subscription detection. Features shared family workspaces, partner invites, auto account detection, duplicate filtering, and real-time balance calculations.",
    stack: ["Next.js", "Supabase", "TypeScript", "Claude API", "Gemini API", "Zustand", "Vercel"],
    links: { live: "https://yogi-finance.vercel.app" },
    visual: { type: "image", src: "/projects/yogi-finance.png" },
    overview:
      "Budgeting apps usually assume one person, one account. I wanted something that worked for a household — where a couple could see shared spending without manually re-entering every transaction from a bank statement PDF.",
    architecture: [
      "Auth is Supabase (email/password) via @supabase/ssr, with a middleware that checks the session on every request and redirects unauthenticated users away from protected routes.",
      "Data lives in Supabase Postgres with row-level security on every table — a families → profiles → accounts/transactions/budgets/goals hierarchy, where RLS policies grant access if a row's family_id matches the caller's family or it's the caller's own user_id.",
      "Statement upload (PDF, CSV, or image) goes to Gemini's multimodal API with a single structured prompt asking for one JSON object: detected account info (bank, type, last 4 digits) plus a normalized, categorized transaction list with confidence scores. Truncated/malformed JSON output is recovered with a regex fallback rather than failing the whole import.",
      "Newly parsed transactions are checked against existing ones using a composite key (date + amount + lowercased description) to flag likely duplicates client-side before import.",
      "Account balances update via a Postgres trigger on transaction insert/update/delete — the database keeps balances consistent automatically, rather than the app recomputing totals on every read.",
      "Claude separately powers subscription detection — scanning 90 days of transactions to flag recurring charges — and is the model behind the app's spending insights.",
      "Family invites generate a shareable token link; accepting one verifies the invite email matches the logged-in user, then updates that profile's family_id — enforced by RLS rather than a separate authorization service.",
    ],
    keyDecisions: [
      "Splitting AI providers by strength rather than using one model for everything: Gemini's multimodal input handles messy PDF/image/CSV statement parsing, while Claude handles the more analytical subscription-detection and insights work.",
      "Balance correctness pushed into the database (a Postgres trigger) instead of application code — it can't drift out of sync with the transaction log, regardless of which code path wrote the transaction.",
      "Client-side duplicate detection with a simple composite key instead of a heavier fuzzy-matching system — cheap, fast, and covers the common case (re-uploading the same statement) without needing a background job.",
    ],
    challenges: [
      "Handling truncated LLM JSON output when a statement has many transactions and the model's response gets cut off mid-array — solved with regex-based partial-array recovery rather than failing the entire import.",
      "Modeling real household edge cases correctly: a spouse only \"counts\" for shared visibility if they're actually joining the family workspace, and someone can't join a second family while still in one — both enforced through RLS policies rather than trusted to the UI.",
      "Honest note: this project went through an earlier prototype (a vanilla PWA with Firebase/Firestore and full offline support) before being rebuilt on Next.js + Supabase. The current version doesn't have the old prototype's offline support yet — a good next step.",
    ],
  },
  {
    slug: "second-brain-bot",
    title: "2nd Brain Bot",
    category: "AI & Automation",
    year: "2026",
    status: "Live",
    onHomepage: false,
    featured: false,
    accent: "purple",
    description:
      "Telegram bot connected to my Obsidian vault. Ask it anything about my notes, projects, career plans — it retrieves and summarises from my personal knowledge base using Claude AI.",
    stack: ["Python", "Claude API", "Telegram Bot API", "GitHub API", "Modal", "Google Calendar API"],
    links: { github: "https://github.com/sazanyogi" },
    visual: { type: "chat" },
    overview:
      "I keep years of notes, project plans, and career research in Obsidian, but searching through hundreds of markdown files by hand doesn't scale. 2nd Brain Bot is a Telegram bot that reads my actual vault and answers questions about it in plain language — and can also log new notes or calendar events just from a message.",
    architecture: [
      "Telegram sends every message to a Modal-hosted FastAPI webhook. The webhook immediately fires a separate Modal function with .spawn() — a fire-and-forget dispatch — and returns instantly, so slow Claude/GitHub calls never risk Telegram's webhook timeout.",
      "Slash commands (/goals, /focus, /inbox, /find, /todo, and more) route to specific handlers. Anything else is sent to Claude with a prompt that forces strict JSON output, classifying the message as either a note (with folder/filename/tags) or a calendar event (with date/time/duration).",
      "There's no vector database or embeddings at all — the Obsidian vault is a GitHub repo, and retrieval happens live via the GitHub API: fetching a known file directly, recursively walking the whole tree for keyword search, or walking commit history to infer \"recent notes.\" It's direct file access over an API, not semantic search.",
      "New notes are upserted — the bot tries to fetch an existing file at the target path first and updates it, falling back to creating a new one, so re-sending a similarly named note doesn't create a duplicate.",
      "Google Calendar access uses a refresh-token pattern: a one-time, local, interactive OAuth consent produces a token that's stored as a Modal secret, and the deployed function silently refreshes it on every cold start — no re-authentication needed in production.",
    ],
    keyDecisions: [
      "Fire-and-forget webhook dispatch specifically to work around serverless request timeouts — a very reusable pattern for any bot backed by slow LLM/API calls on a platform like Modal.",
      "Treating GitHub as the \"filesystem\": since Modal functions are ephemeral with no persistent local disk, the vault genuinely can't be mounted — going through the GitHub API directly turned out to be simpler than standing up a separate synced storage layer.",
      "One-time interactive OAuth, then refresh-token-only in production — avoids ever needing a browser-based consent flow inside a serverless function, which isn't really possible anyway.",
    ],
    challenges: [
      "No local filesystem access in a serverless environment — solved by treating the vault's GitHub-hosted source of truth as directly queryable rather than trying to sync/cache it.",
      "Context window management is intentionally simple right now — long notes are hard-truncated by character count rather than summarized or chunked, which works today but is the clearest next improvement as the vault grows.",
    ],
  },
  {
    slug: "this-portfolio",
    title: "This Portfolio",
    category: "Web App",
    year: "2026",
    status: "Live",
    onHomepage: false,
    featured: false,
    accent: "purple",
    description:
      "You're looking at it. Rebuilt from plain HTML to Next.js with a full design system, dark/light mode, custom cursor, contact form, and auto-deploy via Vercel.",
    stack: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion", "Resend", "Vercel"],
    links: { live: "https://sazan.com.np", github: "https://github.com/sazanyogi/sazan-portfolio" },
    visual: { type: "image", src: "/projects/portfolio.png" },
    overview:
      "This is the site you're on. It started as a static HTML page and has been rebuilt into a full Next.js application — partly as a portfolio, partly as its own case study in iterating on a personal project over time.",
    architecture: [
      "Next.js 16 App Router, with a public marketing site, a private /me dashboard behind a proxy-based auth guard (src/proxy.ts, using Next.js's newer \"Proxy\" convention — the renamed successor to Middleware), and a handful of API routes for contact form submission, login/logout, and PDF uploads.",
      "The entire visual system — colors, fonts, spacing — is driven by CSS custom properties in globals.css, swapped via a data-theme attribute for light/dark mode, rather than a CSS-in-JS or Tailwind-only theming approach.",
      "A custom cursor (a lerped \"ring\" following a fixed \"dot\") replaces the native cursor site-wide, implemented with requestAnimationFrame and direct DOM style mutation for performance rather than re-rendering React state on every mouse move.",
      "The contact form posts to a Route Handler that rate-limits by IP (in-memory, 3 requests/hour), escapes user input before building an HTML email, and sends it via Resend.",
      "Deployed on Vercel with security headers (CSP, X-Frame-Options, Permissions-Policy) configured in next.config.ts, and images served from /public alongside a few Vercel Blob-backed uploads for the private dashboard.",
    ],
    keyDecisions: [
      "Proxy over Middleware: Next.js 16 deprecated the middleware.ts convention in favor of proxy.ts — the auth guard for the private dashboard was migrated to the new convention rather than left on a deprecated API.",
      "High-performance cursor: driving the follower ring via requestAnimationFrame + direct style writes instead of React state avoids a re-render on every mousemove event, which matters for a full-page persistent effect.",
      "CSS custom properties for theming instead of duplicating styles per theme — every component reads var(--bg), var(--text), etc., so adding or adjusting a theme is a one-file change.",
    ],
    challenges: [
      "Getting Next.js 16's newer conventions right — this codebase intentionally tracks a very new Next.js version, so some patterns (like the middleware-to-proxy migration) needed checking against the framework's own docs rather than relying on older training data.",
      "Keeping the visual design system consistent across a growing number of independently-styled sections (hero, services, projects, about, contact) by converging on shared primitives — accent colors, chip styles, card treatments — reused throughout rather than one-off per section.",
    ],
  },
  {
    slug: "maple-everest-fc",
    title: "Maple Everest FC",
    category: "Web App",
    year: "2026",
    status: "Live",
    onHomepage: false,
    featured: false,
    accent: "pink",
    description:
      "Club site for Maple Everest FC, a Nepali-Canadian football club in Mississauga — club story, events, and photo galleries from tournaments and community events, built as a fast, framework-free static site.",
    stack: ["HTML", "CSS", "Vanilla JS", "IntersectionObserver"],
    links: { live: "https://mapleverest.com/" },
    visual: { type: "image", src: "/projects/maple-everest.png" },
    overview:
      "Maple Everest FC needed a club site that could be shipped fast and handed off easily, without needing a developer on hand to make small edits. It's a plain HTML/CSS/JS site — no framework, no build step — covering the club's story, events, and photo galleries from tournaments and community events.",
    architecture: [
      "Four fully self-contained HTML pages (the main site plus three standalone gallery pages), each with its own inlined <style> and <script> — no shared templating, no build tooling, deployable by uploading files directly.",
      "The homepage is a single-page layout: hero with a Ken Burns background animation, a stats bar, an about section, a team section, an events section linking out to each gallery, an embedded 12-photo highlight slider, and a contact section — all revealed on scroll via IntersectionObserver-driven animations.",
      "Two hand-rolled photo gallery UIs, both built from scratch without a lightbox library: a homepage carousel (transform-based slider with dot indicators, thumbnail strip, swipe and keyboard support, autoplay) and standalone gallery pages using a CSS columns masonry grid with category filter tabs and their own full-screen lightbox.",
      "Theming runs entirely on CSS custom properties (club colors, spacing) with CSS Grid/Flexbox layout, clamp()-based fluid type, and three responsive breakpoints handling the switch to a mobile hamburger nav and stacked grids.",
    ],
    keyDecisions: [
      "Plain HTML over a framework, deliberately: for a low-traffic community club site, zero build tooling means it's simple to host and easy to hand off for small text/image edits without needing a developer involved.",
      "Building both gallery UI patterns (embedded slider + standalone masonry pages) from scratch in vanilla JS instead of pulling in a lightbox library — keeps the page dependency-free at the cost of writing more custom interaction code.",
    ],
    challenges: [
      "Duplicating nav/footer markup and CSS across all four pages, since there's no shared templating layer — the trade-off that comes with the zero-build-step approach, and the clearest place a lightweight static-site generator would help if the site grows.",
      "Honest lesson: the standalone gallery pages don't lazy-load their images (unlike the homepage slider, which does) — with 70 total gallery photos, some as large as 600KB straight from the camera, that's a real performance gap worth fixing next, along with resizing/compressing the source images.",
    ],
  },
  {
    slug: "kamal-drives",
    title: "Kamal Drives",
    category: "Web App",
    year: "2026",
    status: "Live",
    onHomepage: false,
    featured: false,
    accent: "cyan",
    description:
      "Marketing site for a certified driving instructor serving Brampton & Mississauga — a fast, single-page Next.js site built with zero UI dependencies, built to convert visitors into booked lessons.",
    stack: ["Next.js", "TypeScript", "CSS Modules"],
    links: { live: "https://www.drivewithkamal.com/", github: "https://github.com/sazanyogi/drivewithkamal" },
    visual: { type: "image", src: "/projects/kamal-drives.png" },
    overview:
      "A client project for a certified driving instructor in the GTA. The brief was simple: a fast, credible marketing site that makes it easy for a prospective student to book a lesson, without over-engineering a site that only needs to do one job well.",
    architecture: [
      "A single route (app/page.tsx) rendering Navbar, Hero, About, Services, Why Choose Me, Testimonials, and Contact in order, with pure anchor-scroll navigation (scroll-behavior: smooth) — no separate pages, no routing complexity for a site this size.",
      "Every section is its own component with a co-located CSS Module, layered on top of a shared global design-token system (CSS custom properties for color, spacing, radius, shadow) plus a few reusable utility classes (glass-card, glow-orb, btn) — a lightweight design system without a UI framework.",
      "Content (services offered, testimonials, contact details) is modeled as typed local arrays of objects mapped straight to JSX — a simple \"data as code\" pattern instead of pulling in a CMS for content that rarely changes.",
      "Four parallel, zero-friction contact paths — a booking form, a WhatsApp deep link, tel:, and mailto: — rather than funneling every visitor through one channel.",
      "Only the Navbar, Hero, and Contact components are Client Components; everything else renders as a Server Component by default, keeping shipped JavaScript minimal for a marketing site where load speed affects conversion.",
    ],
    keyDecisions: [
      "CSS Modules instead of Tailwind or a component library — for a small, fully custom design with no repeated complex components, plain scoped CSS was less overhead than adopting a framework.",
      "Zero runtime dependencies beyond Next.js and React itself — no form library, animation library, or analytics SDK — deliberately minimal for a small business site that needs to load fast and stay cheap to maintain.",
      "Multiple contact channels (form, WhatsApp, phone, email) instead of one funnel, since a local service business benefits more from meeting a prospective client on whichever channel they already prefer.",
    ],
    challenges: [
      "Building against a genuinely new Next.js release meant double-checking a few conventions against the framework's own docs rather than trusting older tutorials or training data.",
      "Honest next step: the booking form currently only updates its own UI state on submit — wiring it to a real email or booking service is the clear next piece of work before it's fully production-complete.",
    ],
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return PROJECTS.find((p) => p.slug === slug);
}

export function getAdjacentProjects(slug: string): { prev: Project | null; next: Project | null } {
  const withSlugs = PROJECTS.filter((p) => p.slug);
  const idx = withSlugs.findIndex((p) => p.slug === slug);
  return {
    prev: idx > 0 ? withSlugs[idx - 1] : null,
    next: idx >= 0 && idx < withSlugs.length - 1 ? withSlugs[idx + 1] : null,
  };
}
